### ISSUE TITLE
Error Faced in Rock, Paper & Scissor

### ISSUE THREAD

**Issue by 149000218-myseneca** [149000218-myseneca/Group-Lab#1]
Error Faced was :- 

"$ python3 MainGame.py
  File "D:\SENECA COLLEGE\Sem 4\OPS445\Assignment\Group-Lab\MainGame.py", line 18
    else:
         ^
IndentationError: unindent does not match any outer indentation level "

This is an IndentationError which caused by mismatch of any elseif loop. This shows an error on line 18 which is my if-elseif-else parameter on which the logic of rock is described. I have to update or have to make changes on elseif parameter of "scissors".

**Comment by darshit8502-kali** [comment]
Solved Successfully
